QLBanTraiCay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('TraiCay.urls'))
]

TraiCay/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.home, name='TrangChu'),
    path('dangnhap/', auth_views.LoginView.as_view(template_name='dangnhap.html', next_page='/'), name='DangNhap'),
    path('dangxuat/', auth_views.LogoutView.as_view(next_page='/'), name='DangXuat'),
    path('dangky/', views.dangky, name='DangKy'),
    path('home/', views.home, name='TrangChu'),
    path('loai/<str:id>', views.loc_theo_loai, name='LocTheoLoai'),
    path('timkiem/', views.tim_kiem, name='TimKiem'),
    path('sanpham/<str:id>', views.sanpham, name='SanPham'),
    path('giohang/', views.giohang, name='GioHang'),
    path('taikhoan/', views.taikhoan, name='TaiKhoan'),
    path('dathang/kiemtra', views.kiem_tra_thong_tin_dat_hang, name='KiemTraTTDatHang'),
    path('dathang/chitiet', views.tt_dat_hang, name='TTDatHang'),
    path('dathang/thanhtoan', views.thanh_toan, name='ThanhToan'),
    path('dathang/thanhcong', views.thanh_toan_thanh_cong, name='TToanThanhCong'),
    path('dathang/thatbai', views.thanh_toan_that_bai, name='TToanThatBai'),
    path('hoadon/<str:hd>', views.chi_tiet_hd, name='ChiTietHD'),
    path('hoadon/xoa/<str:hd>', views.xoa_don_hang, name='XoaDonHang'),

    path('dsLoai', views.list, name='dsLoai'),
    path('dsSanPham', views.list_product, name='dsSanPham'),
    path('dsKho', views.list_Kho, name='dsKho'),
    path('ThemLoai', views.ThemLoai, name='ThemLoai'),
    path('XoaLoai', views.xoa_loai, name='XoaLoai'),
    path('SuaLoai', views.SuaLoai, name='SuaLoai'),
    path('ThemSP', views.ThemSP, name='ThemSP'),
    path('XoaSP', views.XoaSP, name='XoaSP'),
    path('SuaSP', views.SuaSP, name='SuaSP'),
    path('ChiTietKho/<str:Mk>/', views.ChiTiet_Kho, name='ChiTietKho'),

    path('api/loai/', views.getLoai, name='GetLoai'),
    path('api/timkiem/', views.getTimKiem, name='GetTimKiem'),
    path('api/giohang/them', views.them_gio_hang, name='ThemGioHang'),
    path('api/giohang/capnhat', views.get_so_luong, name='GetSoLuong'),
    path('api/giohang/xoa', views.xoa_sanpham_gio_hang, name='XoaGioHang'),
    path('api/giohang/capnhatsoluong', views.cap_nhat_so_luong, name='CapNhatSoLuong'),
    path('api/taikhoan/doimatkhau', views.doi_mat_khau, name='DoiMatKhau'),
    path('api/taikhoan/capnhat', views.sua_thong_tin_kh, name='SuaThongTin'),
    path('api/donhang/timkiem', views.get_hoa_don, name='TimHoaDon'),
]

TraiCay/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Custom user

#############
class Loai(models.Model):
    MaLoai = models.CharField(max_length=10, primary_key=True)
    TenLoai = models.CharField(max_length=100, unique=True)

class SanPham(models.Model):
    MaSP = models.CharField(max_length=10, primary_key=True)
    MaLoai = models.ForeignKey(Loai, on_delete=models.SET_NULL, null=True)
    TenSP = models.CharField(max_length=100, unique=True)
    DonGia = models.DecimalField(max_digits=10, decimal_places=2)
    MoTa = models.TextField()

    def HinhAnh(self):
        hinhanhsp = self.hinhanhsp_set.first()
        return hinhanhsp.HinhAnh if hinhanhsp else None

    def TatCaHinhAnh(self):
        return self.hinhanhsp_set.all()

    def TonKho(self):
        return sum([chitiet.SoLuongTon for chitiet in self.chitietkho_set.all()])

class HinhAnhSP(models.Model):
    SanPham = models.ForeignKey(SanPham, on_delete=models.SET_NULL, null=True)
    HinhAnh = models.TextField()

class KhachHang(models.Model):
    MaKH = models.CharField(max_length=10, primary_key=True)
    TenKH = models.CharField(max_length=100)
    SDT = models.CharField(max_length=20)
    Email = models.CharField(max_length=100)
    DiaChi = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

class NhanVien(models.Model):
    MaNV = models.CharField(max_length=10, primary_key=True)
    TenNV = models.CharField(max_length=100)
    SDT = models.CharField(max_length=20)
    Email = models.CharField(max_length=100)
    DiaChi = models.CharField(max_length=100)

class NhaCungCap(models.Model):
    MaNCC = models.CharField(max_length=10, primary_key=True)
    TenNCC = models.CharField(max_length=100)
    DiaChi = models.CharField(max_length=100)
    Email = models.CharField(max_length=100)
    SDT = models.CharField(max_length=20)

class HoaDon(models.Model):
    MaHD = models.CharField(max_length=10, primary_key=True)
    MaKH = models.ForeignKey(KhachHang, on_delete=models.SET_NULL, null=True)
    NgayMua = models.DateField()
    TongTien = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    DiaChiGiao = models.CharField(max_length=100, null=True)
    PhuongThucThanhToan = models.CharField(max_length=10, null=True)
    TrangThai = models.CharField(max_length=100, null=True)

class ChiTietHoaDon(models.Model):
    MaHD = models.ForeignKey(HoaDon, on_delete=models.SET_NULL, null=True)
    MaSP = models.ForeignKey(SanPham, on_delete=models.SET_NULL, null=True)
    SoLuong = models.IntegerField(default=0)
    DonGia = models.DecimalField(max_digits=10, decimal_places=2)

class Kho(models.Model):
    MaKho = models.CharField(max_length=10, primary_key=True)
    TenKho = models.CharField(max_length=100)
    DiaChiKho = models.CharField(max_length=100)
    SDT = models.CharField(max_length=20)

class ChiTietKho(models.Model):
    MaKho = models.ForeignKey(Kho, on_delete=models.SET_NULL, null=True)
    MaSP = models.ForeignKey(SanPham, on_delete=models.SET_NULL, null=True)
    SoLuongTon = models.IntegerField(default=0)

class PhieuNhapHang(models.Model):
    MaPNH = models.CharField(max_length=10, primary_key=True)
    MaNCC = models.ForeignKey(NhaCungCap, on_delete=models.SET_NULL, null=True)
    NgayNhap = models.DateField()
    TongTien = models.DecimalField(max_digits=10, decimal_places=2)

class ChiTietPhieuNhap(models.Model):
    MaPNH = models.ForeignKey(PhieuNhapHang, on_delete=models.SET_NULL, null=True)
    MaSP = models.ForeignKey(SanPham, on_delete=models.SET_NULL, null=True)
    DonGia = models.DecimalField(max_digits=10, decimal_places=2)

class Slider(models.Model):
    HinhAnh = models.TextField()
    Link = models.TextField()

class GioHang(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    SanPham = models.ForeignKey(SanPham, on_delete=models.CASCADE, null=False)
    SoLuong = models.IntegerField(default=0, null=False)

TraiCay/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

import json
import datetime

from .models import *
from .forms import *

from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import *

# Create your views here.
def dangky(request):
    form = FormDangKy
    if request.method == 'POST':
        form = FormDangKy(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect('/')

    return render(request, 'dangky.html', {'form': form})

def home(request):
    Home_Fruits = []
    DSLoai = Loai.objects.all()[:7]
    for loai in DSLoai:
        sanpham = SanPham.objects.filter(MaLoai = loai)
        fruits = {'loai': loai, 'fruits': sanpham}
        Home_Fruits.append(fruits)

    Sliders = Slider.objects.all()

    return render(request, 'home.html', {'Home_Fruits' : Home_Fruits, 'Sliders': Sliders})

def loc_theo_loai(request, id):
    loai = None
    if id == 'all':
        sanpham = SanPham.objects.all()
    else:
        loai = get_object_or_404(Loai, pk=id)
        sanpham = SanPham.objects.filter(MaLoai = loai)

    sort = request.GET.get('s')
    if sort == 'random':
        sanpham = sanpham.order_by('?')
    elif sort == 'p-asc':
        sanpham = sanpham.order_by('DonGia')
    elif sort == 'p-desc':
        sanpham = sanpham.order_by('-DonGia')
    elif sort == 'n-asc':
        sanpham = sanpham.order_by('TenSP')
    elif sort == 'n-desc':
        sanpham = sanpham.order_by('-TenSP')

    # phân trang
    limit = 20
    page = request.GET.get('page', 1)

    sanpham_paginator = Paginator(sanpham, limit)
    try:
        sanpham_page = sanpham_paginator.get_page(page)
    except PageNotAnInteger:
        sanpham_page = sanpham_paginator.get_page(1)
    except EmtyPage:
        sanpham_page = sanpham_paginator.get_page(sanpham_paginator.num_pages)

    current_page = sanpham_page.number
    num_pages = sanpham_paginator.num_pages
    page_range = sanpham_paginator.page_range
    previous_page = current_page - 1
    next_page = current_page + 1
    start_page = current_page - 1 if current_page > 1 else 1
    end_page = current_page + 1 if current_page < num_pages else num_pages

    context = {
        'Fruits': sanpham_page,
        'current_page': current_page,
        'num_pages': num_pages,
        'page_range': page_range,
        'previous_page': previous_page,
        'next_page': next_page,
        'start_page': start_page,
        'end_page': end_page,
        'Loai': loai
    }

    return render(request, 'loai.html', context)

def tim_kiem(request):
    query = request.GET.get('q')
    if query:
        sanpham = SanPham.objects.filter(TenSP__icontains=query)
    else:
        sanpham = SanPham.objects.all()

    sort = request.GET.get('s')
    if sort == 'random':
        sanpham = sanpham.order_by('?')
    elif sort == 'p-asc':
        sanpham = sanpham.order_by('DonGia')
    elif sort == 'p-desc':
        sanpham = sanpham.order_by('-DonGia')
    elif sort == 'n-asc':
        sanpham = sanpham.order_by('TenSP')
    elif sort == 'n-desc':
        sanpham = sanpham.order_by('-TenSP')

    # phân trang
    limit = 20
    page = request.GET.get('page', 1)

    sanpham_paginator = Paginator(sanpham, limit)
    try:
        sanpham_page = sanpham_paginator.get_page(page)
    except PageNotAnInteger:
        sanpham_page = sanpham_paginator.get_page(1)
    except EmtyPage:
        sanpham_page = sanpham_paginator.get_page(sanpham_paginator.num_pages)

    current_page = sanpham_page.number
    num_pages = sanpham_paginator.num_pages
    page_range = sanpham_paginator.page_range
    previous_page = current_page - 1
    next_page = current_page + 1
    start_page = current_page - 1 if current_page > 1 else 1
    end_page = current_page + 1 if current_page < num_pages else num_pages

    context = {
        'value': query,
        'Fruits': sanpham_page,
        'current_page': current_page,
        'num_pages': num_pages,
        'page_range': page_range,
        'previous_page': previous_page,
        'next_page': next_page,
        'start_page': start_page,
        'end_page': end_page,
    }

    return render(request, 'timkiem.html', context)

def sanpham(request, id):
    sanpham = get_object_or_404(SanPham,  pk=id)
    loai = sanpham.MaLoai
    spkho = ChiTietKho.objects.filter(MaSP=sanpham)

    return render(request, 'sanpham.html', {'Loai': loai, 'Fruit': sanpham})

def giohang(request):
    user = request.user
    if user and user.is_authenticated:
        giohang = GioHang.objects.filter(user = user)
        for gh in giohang:
            if gh.SanPham.TonKho() <= 0:
                gh.delete()

        giohang = GioHang.objects.filter(user = user)
        total = sum([gh.SanPham.DonGia * gh.SoLuong for gh in giohang])
        
        try:
            kh = KhachHang.objects.get(user=user)
            return render(request, 'giohang.html', {'Cart': giohang, 'TongTien': total, 'KH': kh})
        except Exception:
            pass
        return render(request, 'giohang.html', {'Cart': giohang, 'TongTien': total})
    else:
        session_cart = request.session.get('cart', None)
        cart = []
        total = 0
        if session_cart:
            for c in session_cart:
                sanpham = get_object_or_404(SanPham, pk=c['MaSP'])
                if sanpham.TonKho() <= 0:
                    session_cart.remove(c)
                    request.session['cart'] = session_cart
                else:
                    total += sanpham.DonGia * c['SoLuong']
                    cart.append({'SanPham': sanpham, 'SoLuong': c['SoLuong']})
            return render(request, 'giohang.html', {'Cart': cart, 'TongTien': total})

    return render(request, 'giohang.html')


### 
@api_view(['POST'])
def kiem_tra_thong_tin_dat_hang(request):
    fullname = request.data.get('name')
    phone = request.data.get('phone')
    address = request.data.get('address')
    shipmed = request.data.get('shipmed')
    note = request.data.get('note')

    if not fullname or not phone or not shipmed:
        return Response({'success': False, 'error': 'Vui lòng nhập đầy đủ thông tin'}, status=status.HTTP_200_OK)

    if shipmed == 'COD':
        if not address:
            return Response({'success': False, 'error': 'Vui lòng nhập địa chỉ'}, status=status.HTTP_200_OK)

    request.session['order_temp'] = {'shipmed': shipmed, 'address': address, 'note': note}
    return Response({'success': True})


def tt_dat_hang(request):
    user = request.user
    if not user or not user.is_authenticated:
        return HttpResponseRedirect('/giohang')

    order_temp = request.session.get('order_temp')
    if not order_temp:
        return HttpResponseRedirect('/giohang') 

    kh = KhachHang.objects.get(user=user)
    giohang = GioHang.objects.filter(user = user)
    total = sum([gh.SanPham.DonGia * gh.SoLuong for gh in giohang])
    return render(request, 'ttdathang.html', {'TongTien': total, 'KH': kh, 'OrderTemp': order_temp})


@api_view(['POST'])
def thanh_toan(request):
    user = request.user
    if not user or not user.is_authenticated:
        return Response({'success': False, 'url': '/giophang'}, status=status.HTTP_200_OK)

    giohang = GioHang.objects.filter(user=user)
    if not giohang:
        return Response({'success': False, 'url': '/giophang'}, status=status.HTTP_200_OK)

    count_het_hang = 0
    errors = []
    for gh in giohang:
        if gh.SanPham.TonKho() <= 0:
            errors.append('Sản phẩm' + gh.SanPham.TenSP +  'đã hết hàng.')
            count_het_hang += 1

    if count_het_hang > 0:
        return Response({'success': False, 'error': errors}, status=status.HTTP_200_OK)

    order_temp = request.session.get('order_temp')
    if not order_temp:
        return Response({'success': False, 'url': '/giophang'}, status=status.HTTP_200_OK)

    payment_med = request.data.get('payment_med')

    if payment_med != 'COD':
        return Response(status=status.HTTP_403_FORBIDDEN)
    order_id = random_ma_donhang()
    address = order_temp['shipmed'] if order_temp['shipmed'] != 'COD' else order_temp['address']
    total_price = sum([gh.SanPham.DonGia * gh.SoLuong for gh in giohang])

    customer = KhachHang.objects.get(user=user)
    HoaDon.objects.create(MaHD=order_id, MaKH=customer, NgayMua=datetime.datetime.now(), TongTien=total_price, 
            DiaChiGiao=address, PhuongThucThanhToan=payment_med, TrangThai='Chờ thanh toán')
    hoadon = HoaDon.objects.get(MaHD=order_id, MaKH=customer)

    for gh in giohang:
        ChiTietHoaDon.objects.create(MaSP=gh.SanPham, DonGia=gh.SoLuong * gh.SanPham.DonGia, MaHD=hoadon, SoLuong=gh.SoLuong)
        kho = ChiTietKho.objects.filter(MaSP=SanPham.objects.get(MaSP=gh.SanPham.MaSP))
        total_qty_remain = 0
        for k in kho:
            if k.SoLuongTon < gh.SoLuong:
                total_qty_remain = gh.SoLuong - k.SoLuongTon
                k.SoLuongTon = 0
            else:
                total_qty_remain = k.SoLuongTon - gh.SoLuong
                k.SoLuongTon -= gh.SoLuong

            k.save()

            if total_qty_remain <= 0:
                break

        gh.delete()

    del request.session['order_temp']
    request.session.modified = True

    if payment_med == 'COD':
        if hoadon:

TraiCay/templates/admin_pages/ChiTietKho.html
{% extends "layout/admin_layout/layout.html" %}

{% block title %}Chi tiết kho{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Chi tiết kho</h2>
    <table class="table table-hover table-sm w-100 mx-auto">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Số lượng tồn</th>
                <th scope="col">Mã kho</th>
                <th scope="col">Mã sản phẩm</th>
            </tr>
        </thead>
        <tbody>
            {% for ct in ds_ctKho %}
            <tr>
                <td>{{ ct.SoLuongTon   }}</td>
                <td>{{ ct.MaKho.MaKho }}</td>
                <td>{{ ct.MaSP.TenSP }}</td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

TraiCay/templates/admin_pages/SuaLoai.html
{% extends "layout/admin_layout/layout.html" %} 
{% block title %} Sửa loại {% endblock %} 
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Sửa loại</h2>
    <form action="{% url 'SuaLoai' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="MaLoai">Mã loại:</label>
            {{ form.MaLoai }}
            {% if form.MaLoai.errors %}
                <div class="text-danger">{{ form.MaLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="TenLoai">Tên loại:</label>
            {{ form.TenLoai }}
            {% if form.TenLoai.errors %}
                <div class="text-danger">{{ form.TenLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Sửa loại" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock %}

TraiCay/templates/admin_pages/SuaSP.html
{% extends "layout/admin_layout/layout.html" %}
{% block title %} Sửa sản phẩm {% endblock %}
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Sửa sản phẩm</h2>
    <form action="{% url 'SuaSP' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="MaSP">Mã sản phẩm:</label>
            {{ form.MaSP }}
            {% if form.MaSP.errors %}
                <div class="text-danger">{{ form.MaSP.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="MaLoai">Mã loại:</label>
            {{ form.MaLoai }}
            {% if form.MaLoai.errors %}
                <div class="text-danger">{{ form.MaLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="TenSP">Tên sản phẩm:</label>
            {{ form.TenSP }}
            {% if form.TenSP.errors %}
                <div class="text-danger">{{ form.TenSP.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="DonGia">Đơn giá:</label>
            {{ form.DonGia }}
            {% if form.DonGia.errors %}
                <div class="text-danger">{{ form.DonGia.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="MoTa">Mô tả:</label>
            {{ form.MoTa }}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Sửa sản phẩm" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock %}

TraiCay/templates/admin_pages/ThemLoai.html
{% extends "layout/admin_layout/layout.html" %} 
{% block title %} Thêm loại {% endblock %} 
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Thêm loại</h2>
    <form action="{% url 'ThemLoai' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="MaLoai">Mã loại:</label>
            {{ form.MaLoai }}
            {% if form.MaLoai.errors %}
                <div class="text-danger">{{ form.MaLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="TenLoai">Tên loại:</label>
            {{ form.TenLoai }}
            {% if form.TenLoai.errors %}
                <div class="text-danger">{{ form.TenLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Thêm loại" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock %}

TraiCay/templates/admin_pages/ThemSP.html
{% extends "layout/admin_layout/layout.html" %}
{% block title %} Thêm sản phẩm {% endblock %}
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Thêm sản phẩm</h2>
    <form action="{% url 'ThemSP' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="MaSP">Mã sản phẩm:</label>
            {{ form.MaSP }}
            {% if form.MaSP.errors %}
                <div class="text-danger">{{ form.MaSP.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="MaLoai">Mã loại:</label>
            {{ form.MaLoai }}
            {% if form.MaLoai.errors %}
                <div class="text-danger">{{ form.MaLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="TenSP">Tên sản phẩm:</label>
            {{ form.TenSP }}
            {% if form.TenSP.errors %}
                <div class="text-danger">{{ form.TenSP.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="DonGia">Đơn giá:</label>
            {{ form.DonGia }}
            {% if form.DonGia.errors %}
                <div class="text-danger">{{ form.DonGia.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="MoTa">Mô tả:</label>
            {{ form.MoTa }}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Thêm sản phẩm" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock %}

TraiCay/templates/admin_pages/XoaLoai.html
{% extends "layout/admin_layout/layout.html" %}
{% block title %} Xóa loại {% endblock %}
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Xóa loại</h2>
    <form id="xoaLoaiForm" action="{% url 'XoaLoai' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="id_MaLoai">Mã loại:</label>
            {{ form.MaLoai }}
            {% if form.MaLoai.errors %}
                <div class="text-danger">{{ form.MaLoai.errors }}</div>
            {% endif %}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Xóa loại" class="btn btn-danger" onclick="return confirmXoaLoai()">
        </div>
    </form>
</div>

<script type="text/javascript">
function confirmXoaLoai() {
    return confirm("Bạn có chắc chắn muốn xóa loại này không?");
}
</script>
{% endblock %}

TraiCay/templates/admin_pages/XoaSP.html
{% extends "layout/admin_layout/layout.html" %} 
{% block title %} Xóa Sản phẩm {% endblock %} 
{% block content %}
<div class="container mt-4">
    <h2 class="w-100 p-3 text-danger">Xóa loại</h2>
    <form action="{% url 'XoaSP' %}" method="POST" class="w-50 border p-4 shadow-sm bg-light">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="MaSP">Mã sản phẩm:</label>
            {{ form.MaSP }}
            {% if form.MaSP.errors %}
                <div class="text-danger">{{ form.MaSP.errors }}</div>
            {% endif %}
        </div>
        <div class="text-center mt-4">
            <input type="submit" value="Xóa sản phẩm" class="btn btn-primary" onclick="return confirmXoaSP()">
        </div>
    </form>
</div>
<script type="text/javascript">
    function confirmXoaSP() {
        return confirm("Bạn có chắc chắn muốn xóa sản phẩm này không?");
    }
    </script>
{% endblock %}

TraiCay/templates/admin_pages/dsKho.html
{% extends "layout/admin_layout/layout.html" %}

{% block title %}Danh sách kho{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Danh sách kho</h2>
    <table class="table table-hover table-sm w-100 mx-auto">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Mã kho</th>
                <th scope="col">Tên kho</th>
                <th scope="col">Địa chỉ kho</th>
                <th scope="col">Số điện thoại</th>
            </tr>
        </thead>
        <tbody>
            {% for k in ds_Kho %}
            <tr>
                <td>{{ k.MaKho }}</td>
                <td>{{ k.TenKho }}</td> 
                <td>{{ k.DiaChiKho }}</td>
                <td>{{ k.SDT }}</td>
                <td>
                    <a href="{% url 'ChiTietKho' Mk=k.MaKho %}" class="btn btn-sm btn-primary mx-1">Hiển thị chi tiết kho</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}